#!/usr/bin/env python
import sys

from megacllib import MegaCommandLineClient
import cProfile
import re

def main():
    megaclclient = MegaCommandLineClient()
    if not(megaclclient.run( sys.argv )) :
        sys.exit(1)

if __name__ == '__main__' :
    cProfile.run('main()')

