#!/usr/bin/env python
import sys

from megacllib import MegaCommandLineClient

if __name__ == '__main__' :
    megaclclient = MegaCommandLineClient()
    if not(megaclclient.run( sys.argv )) :
        sys.exit(1)




